name: Deploy to Registry
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      JRE_BASE_IMAGE: ${{ secrets.JRE_BASE_IMAGE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache Scala, SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.ivy2
            ~/.cache/coursier
          key: deploy-to-registry
      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Deploy to Registry
        run: sbt -Ddocker.repository=docker.io/dataplatformlab server/docker:publish
